### ISSUE TITLE
Error while building the resources

### ISSUE THREAD

**Issue by TridevReddy** [dwisiswant0/ppfuzz#10]
Hello. I used the command cargo build --release for building the resources after cloning it in my directory. Everything went fine till nearly 175 resources, later I am getting the following error
<img width="781" alt="error" src="https://user-images.githubusercontent.com/73326725/124404704-af6e4780-dd59-11eb-8d8a-3830fef87a3f.png">

**Comment by mattsse** [comment]
do you have rustfmt available?
https://github.com/rust-lang/rustfmt

chromiumoxide runs this internally after generating all the bindings?

any chance you have the OUT_DIR env var set?

**Comment by TridevReddy** [comment]
Thank you. No it's fine

**Comment by meetgyn** [comment]
I have the same problem in the installation. Did you solve it?
