### ISSUE TITLE
Can not Execute Binary File

### ISSUE THREAD

**Issue by awais922609** [dwisiswant0/ppfuzz#11]
I am using preinstalled version. I have chrome installed too but when i try to execute ppfuzz from /usr/local/bin it says binary not executable and when it is placed somewhere else it says command not found. I have also tried chmod +x ppfuzz command but still same error.

**Comment by dwisiswant0** [comment]
What is your environment?  Which file did you download? Please explain as clearly as possible, @awais922609.

**Comment by awais922609** [comment]
I downloaded X64 arch linux pre-built version from this link https://github.com/dwisiswant0/ppfuzz/releases. When I downloaded it I am unable to run it after even installing dependencies. I also change mode to executable. Also tried to clone it but facing same error.

**Comment by dwisiswant0** [comment]
> I downloaded X64 arch linux pre-built version from this link https://github.com/dwisiswant0/ppfuzz/releases. When I downloaded it I am unable to run it after even installing dependencies. I also change mode to executable. Also tried to clone it but facing same error.

Attaching a screenshot will be more helpful to replicate your problem.

**Comment by awais922609** [comment]
![Capture](https://user-images.githubusercontent.com/69464258/124541168-50343400-de3a-11eb-8102-5fed18c5387b.PNG)
I have clone it and then build it using this command cargo build --release. I am still getting this error which is shown in image.

**Comment by dwisiswant0** [comment]
> ![Capture](https://user-images.githubusercontent.com/69464258/124541168-50343400-de3a-11eb-8102-5fed18c5387b.PNG)
> I have clone it and then build it using this command cargo build --release. I am still getting this error which is shown in image.
> 

Looks like this is a pre-built file and not compiled from `cargo`.

If you have done `cargo build --release`, binary files are in `target/release/ppfuzz`.

**Comment by awais922609** [comment]
Thanks alot man I found it .
