### ISSUE TITLE
The script does not runs in wsl or wsl2

### ISSUE THREAD

**Issue by MR-pentestGuy** [dwisiswant0/ppfuzz#17]
I was thinking of using this tool but this does not works in wsl and wsl2

**Comment by mattsse** [comment]
does building it from source work?

**Comment by MR-pentestGuy** [comment]
Yes i have installed from the source as well . but this is due to browser issues i have installed my browser properly on my wsl and also i have given a proper path but still i see this error 

[ERRO] Unable to launch browser: Request timed out..
i have tried this in both wsl and wsl-2 
\will work out and tell if anything is possible so that you can add them to your repo 

thanks

**Comment by dwisiswant0** [comment]
> Yes i have installed from the source as well . but this is due to browser issues i have installed my browser properly on my wsl and also i have given a proper path but still i see this error 
> 
> [ERRO] Unable to launch browser: Request timed out..
> i have tried this in both wsl and wsl-2 
> \will work out and tell if anything is possible so that you can add them to your repo 
> 
> thanks

This is similar to #9. Also check https://github.com/mattsse/chromiumoxide#troubleshooting for troubleshooting.

**Comment by MR-pentestGuy** [comment]
Well i am still facing the same issue even after i have given the chrome path in my bashrc 
shall i try chromium instead  ??

**Comment by MR-pentestGuy** [comment]
it is not working anyway thanks for the tool

**Comment by MR-pentestGuy** [comment]
well here is the thing you need to do 
export BROWSER=~/.local/bin/chrome 
add the above one in ~/.bashrc file and make sure chrome is present in ~/.local/bin/chrome 
by default it is present
