### ISSUE TITLE
[Enhancement] Latest version download automation  

### ISSUE THREAD

**Issue by bileltechno** [dwisiswant0/ppfuzz#23]
Hi,
first of all I need to thank you for your effort made on this awesome tool.

Can you please delete the version number from the compiled binaries names?
We, in  [reconftw](https://github.com/six2dez/reconftw/blob/dev/install.sh), trying to automate the installation of tools but if the binaries for every new version will have a different name, that's will complicate installing the latest version of ***ppfuzz***.

for exemple the names can be as below:
```.js
ppfuzz-aarch64
ppfuzz-armv7
ppfuzz-linux
ppfuzz-linux-i386
ppfuzz-osx
ppfuzz-windows.exe
```
Otherwise, we need to update the installation script for every new ppfuzz version.
thanks in advnce
Bilel Eljaamii

**Comment by dwisiswant0** [comment]
Hi, @bileltechno. First of all, I won't change that from the cycle. But, GitHub has an [API endpoint](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) to get the last release name.

For your workaround _(e.g. using Bash)_:
```bash
curl -s "https://api.github.com/repos/dwisiswant0/ppfuzz/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
# Output: v1.0.1
```

Another alternative _(if you have [jq](https://stedolan.github.io/jq/))_, simply:
```bash
curl -s "https://api.github.com/repos/dwisiswant0/ppfuzz/releases/latest" | jq -r ".tag_name"
# Output: v1.0.1
```

So, the specific treatment is as follows:
```bash
REPO="dwisiswant0/ppfuzz"
VERSION="$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" | jq -r ".tag_name")"
wget "https://github.com/${REPO}/releases/download/${VERSION}/ppfuzz-${VERSION}-x86_64-unknown-linux-musl.tar.gz"
```

Cheers!
