### ISSUE TITLE
problem install on macbookpro m1

### ISSUE THREAD

**Issue by AzhariRamadhan** [dwisiswant0/ppfuzz#28]
`cargo build --release

   Compiling ppfuzz v1.0.1 (/Users/azhariramadhan/Documents/pentest-tools/reconftw/ppfuzz)
error[E0432]: unresolved imports `clap::crate_authors`, `clap::crate_description`, `clap::crate_name`, `clap::crate_version`
 --> src/parser.rs:5:3
  |
5 |         crate_authors,
  |         ^^^^^^^^^^^^^ no `crate_authors` in the root
6 |         crate_description,
  |         ^^^^^^^^^^^^^^^^^ no `crate_description` in the root
7 |         crate_name,
  |         ^^^^^^^^^^ no `crate_name` in the root
8 |         crate_version,
  |         ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_name`
  --> src/parser.rs:30:4
   |
30 |             crate_name!(), "FILE", "[OPTIONS]"
   |             ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_authors`
  --> src/parser.rs:33:12
   |
33 |             .author(crate_authors!())
   |                     ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> src/parser.rs:34:11
   |
34 |             .about(crate_description!())
   |                    ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_name`
  --> src/parser.rs:35:10
   |
35 |             .name(crate_name!())
   |                   ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_version`
  --> src/parser.rs:36:13
   |
36 |             .version(crate_version!())
   |                      ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
  --> src/parser.rs:32:23
   |
32 |         let app = App::from(yaml)
   |                   --------- ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`
   |                   |
   |                   arguments to this function are incorrect
   |
note: associated function defined here

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `ppfuzz` due to 7 previous errors
`

**Comment by timurokahoot** [comment]
same issue

**Comment by tarunkant** [comment]
I am also experiencing same issue

**Comment by dwisiswant0** [comment]
This issue packed on [v1.0.2](https://github.com/dwisiswant0/ppfuzz/releases/tag/v1.0.2).

**Comment by dwisiswant0** [comment]
This issue packed on [v1.0.2](https://github.com/dwisiswant0/ppfuzz/releases/tag/v1.0.2).
